### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by vinayak-mehta** [camelot-dev/camelot#518]
- [x] Bump version to 1.0.0
- [x] Update installation docs
- [x] Update release.yml
- [x] Update notebooks code

**Comment by vinayak-mehta** [comment]
@bosd can you give me your pypi and readthedocs usernames so I can add you there too?

**Comment by bosd** [comment]
Yes, my user names there are the same there. So `bosd`

**Comment by vinayak-mehta** [comment]
Just sent you invites

**Comment by bosd** [comment]
Thanks,

An optional suggestion. Since we switched to uv. Might as well switch to use ruff.

IIt's still alpha, but made an updated cookiecutter to the one used here with ruff and uv.
https://github.com/bosd/cookiecutter-uv-hypermodern-python

**Comment by vinayak-mehta** [comment]
That's a great idea! I've been also thinking about switching to ruff here because I've been using it for every other project locally.

**Comment by vinayak-mehta** [comment]
I've also been using it as an "on save" hook in my code editor. I tripped myself a bit because the pre-commit github action would fail because it doesn't like the ruff changes. I can update that.

**Comment by vinayak-mehta** [comment]
I just added this trusted published on pypi so that the release.yaml publishes a new version whenever we push a new tag. I will update the release.yml.

![image](https://github.com/user-attachments/assets/b0c90472-5dc1-4d69-9a4f-6d61612eb75b)

**Comment by vinayak-mehta** [comment]
Argh it's somehow trying to publish to Camelot and not camelot-py https://github.com/camelot-dev/camelot/actions/runs/12540270974/job/34967375726

Need to figure out why

**Comment by vinayak-mehta** [comment]
A new version will automatically be published to PyPI whenever we push a new tag @bosd @MartinThoma @foarsitter

**Comment by vinayak-mehta** [comment]
Closing this issue.

**Comment by vinayak-mehta** [comment]
codecov works now, though i'm not able to get the comments to work
